# nginx proxy address - http://172.17.0.1:5055

name: overseerr
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  overseerr:
    image: sctx/overseerr:latest
    pull_policy: always
    container_name: overseerr-app
    restart: always
    logging: *default-logging
    networks:
      - overseerr
    ports:
      - "172.17.0.1:5055:5055"
    environment:
      TZ: ${TZ:-America/New_York}
      LOG_LEVEL: info
    volumes:
      - ./volumes/config/overseerr:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  overseerr:
    external: false
